package kanalony.storage.logic

import kanalony.storage.logic.queries._
import kanalony.storage.logic._

object Queries {
  object hourly_ua_prtn_entryQuery extends hourly_ua_prtn_entryQuery
object minutely_ua_Query extends minutely_ua_Query
object hourly_ua_Query extends hourly_ua_Query
object minutely_ua_prtn_entryQuery extends minutely_ua_prtn_entryQuery
object minutely_ua_clst_entryQuery extends minutely_ua_clst_entryQuery
object hourly_ua_clst_entryQuery extends hourly_ua_clst_entryQuery
object minutely_ua_clst_countryQuery extends minutely_ua_clst_countryQuery
object hourly_ua_clst_countryQuery extends hourly_ua_clst_countryQuery
object minutely_ua_prtn_countryQuery extends minutely_ua_prtn_countryQuery
object hourly_ua_prtn_countryQuery extends hourly_ua_prtn_countryQuery
object minutely_ua_prtn_entry_clst_countryQuery extends minutely_ua_prtn_entry_clst_countryQuery
object hourly_ua_prtn_entry_clst_countryQuery extends hourly_ua_prtn_entry_clst_countryQuery
object minutely_ua_prtn_entry_countryQuery extends minutely_ua_prtn_entry_countryQuery
object hourly_ua_prtn_entry_countryQuery extends hourly_ua_prtn_entry_countryQuery
object minutely_ua_clst_country_cityQuery extends minutely_ua_clst_country_cityQuery
object hourly_ua_clst_country_cityQuery extends hourly_ua_clst_country_cityQuery
object minutely_ua_prtn_country_cityQuery extends minutely_ua_prtn_country_cityQuery
object hourly_ua_prtn_country_cityQuery extends hourly_ua_prtn_country_cityQuery
object minutely_ua_prtn_entry_clst_country_cityQuery extends minutely_ua_prtn_entry_clst_country_cityQuery
object hourly_ua_prtn_entry_clst_country_cityQuery extends hourly_ua_prtn_entry_clst_country_cityQuery
object minutely_ua_prtn_entry_country_cityQuery extends minutely_ua_prtn_entry_country_cityQuery
object hourly_ua_prtn_entry_country_cityQuery extends hourly_ua_prtn_entry_country_cityQuery
object minutely_ua_clst_deviceQuery extends minutely_ua_clst_deviceQuery
object hourly_ua_clst_deviceQuery extends hourly_ua_clst_deviceQuery
object minutely_ua_prtn_deviceQuery extends minutely_ua_prtn_deviceQuery
object hourly_ua_prtn_deviceQuery extends hourly_ua_prtn_deviceQuery
object minutely_ua_prtn_entry_clst_deviceQuery extends minutely_ua_prtn_entry_clst_deviceQuery
object hourly_ua_prtn_entry_clst_deviceQuery extends hourly_ua_prtn_entry_clst_deviceQuery
object minutely_ua_prtn_entry_deviceQuery extends minutely_ua_prtn_entry_deviceQuery
object hourly_ua_prtn_entry_deviceQuery extends hourly_ua_prtn_entry_deviceQuery
object minutely_ua_clst_osQuery extends minutely_ua_clst_osQuery
object hourly_ua_clst_osQuery extends hourly_ua_clst_osQuery
object minutely_ua_prtn_osQuery extends minutely_ua_prtn_osQuery
object hourly_ua_prtn_osQuery extends hourly_ua_prtn_osQuery
object minutely_ua_prtn_entry_clst_osQuery extends minutely_ua_prtn_entry_clst_osQuery
object hourly_ua_prtn_entry_clst_osQuery extends hourly_ua_prtn_entry_clst_osQuery
object minutely_ua_prtn_entry_osQuery extends minutely_ua_prtn_entry_osQuery
object hourly_ua_prtn_entry_osQuery extends hourly_ua_prtn_entry_osQuery
object minutely_ua_clst_browserQuery extends minutely_ua_clst_browserQuery
object hourly_ua_clst_browserQuery extends hourly_ua_clst_browserQuery
object minutely_ua_prtn_browserQuery extends minutely_ua_prtn_browserQuery
object hourly_ua_prtn_browserQuery extends hourly_ua_prtn_browserQuery
object minutely_ua_prtn_entry_clst_browserQuery extends minutely_ua_prtn_entry_clst_browserQuery
object hourly_ua_prtn_entry_clst_browserQuery extends hourly_ua_prtn_entry_clst_browserQuery
object minutely_ua_prtn_entry_browserQuery extends minutely_ua_prtn_entry_browserQuery
object hourly_ua_prtn_entry_browserQuery extends hourly_ua_prtn_entry_browserQuery
object minutely_ua_ptrn_device_clst_osQuery extends minutely_ua_ptrn_device_clst_osQuery
object hourly_ua_ptrn_device_clst_osQuery extends hourly_ua_ptrn_device_clst_osQuery
object minutely_ua_prtn_device_osQuery extends minutely_ua_prtn_device_osQuery
object hourly_ua_prtn_device_osQuery extends hourly_ua_prtn_device_osQuery
object minutely_ua_prtn_entry_device_clst_osQuery extends minutely_ua_prtn_entry_device_clst_osQuery
object hourly_ua_prtn_entry_device_clst_osQuery extends hourly_ua_prtn_entry_device_clst_osQuery
object minutely_ua_prtn_entry_device_osQuery extends minutely_ua_prtn_entry_device_osQuery
object hourly_ua_prtn_entry_device_osQuery extends hourly_ua_prtn_entry_device_osQuery
object minutely_ua_ptrn_os_clst_browserQuery extends minutely_ua_ptrn_os_clst_browserQuery
object hourly_ua_ptrn_os_clst_browserQuery extends hourly_ua_ptrn_os_clst_browserQuery
object minutely_ua_prtn_os_browserQuery extends minutely_ua_prtn_os_browserQuery
object hourly_ua_prtn_os_browserQuery extends hourly_ua_prtn_os_browserQuery
object minutely_ua_prtn_entry_os_clst_browserQuery extends minutely_ua_prtn_entry_os_clst_browserQuery
object hourly_ua_prtn_entry_os_clst_browserQuery extends hourly_ua_prtn_entry_os_clst_browserQuery
object minutely_ua_prtn_entry_os_browserQuery extends minutely_ua_prtn_entry_os_browserQuery
object hourly_ua_prtn_entry_os_browserQuery extends hourly_ua_prtn_entry_os_browserQuery
object hourly_ua_prtn_country_clst_os_browserQuery extends hourly_ua_prtn_country_clst_os_browserQuery
object hourly_ua_prtn_country_clst_osQuery extends hourly_ua_prtn_country_clst_osQuery
object hourly_ua_prtn_country_clst_browserQuery extends hourly_ua_prtn_country_clst_browserQuery
object minutely_ua_clst_domainQuery extends minutely_ua_clst_domainQuery
object hourly_ua_clst_domainQuery extends hourly_ua_clst_domainQuery
object minutely_ua_prtn_domainQuery extends minutely_ua_prtn_domainQuery
object hourly_ua_prtn_domainQuery extends hourly_ua_prtn_domainQuery
object minutely_ua_prtn_entry_clst_domainQuery extends minutely_ua_prtn_entry_clst_domainQuery
object hourly_ua_prtn_entry_clst_domainQuery extends hourly_ua_prtn_entry_clst_domainQuery
object minutely_ua_prtn_entry_domainQuery extends minutely_ua_prtn_entry_domainQuery
object hourly_ua_prtn_entry_domainQuery extends hourly_ua_prtn_entry_domainQuery
object minutely_ua_clst_referrerQuery extends minutely_ua_clst_referrerQuery
object hourly_ua_clst_referrerQuery extends hourly_ua_clst_referrerQuery
object minutely_ua_prtn_referrerQuery extends minutely_ua_prtn_referrerQuery
object hourly_ua_prtn_referrerQuery extends hourly_ua_prtn_referrerQuery
object minutely_ua_prtn_entry_clst_referrerQuery extends minutely_ua_prtn_entry_clst_referrerQuery
object hourly_ua_prtn_entry_clst_referrerQuery extends hourly_ua_prtn_entry_clst_referrerQuery
object minutely_ua_prtn_entry_referrerQuery extends minutely_ua_prtn_entry_referrerQuery
object hourly_ua_prtn_entry_referrerQuery extends hourly_ua_prtn_entry_referrerQuery
object minutely_ua_ptrn_domain_clst_referrerQuery extends minutely_ua_ptrn_domain_clst_referrerQuery
object hourly_ua_ptrn_domain_clst_referrerQuery extends hourly_ua_ptrn_domain_clst_referrerQuery
object minutely_ua_prtn_entry_domain_clst_referrerQuery extends minutely_ua_prtn_entry_domain_clst_referrerQuery
object hourly_ua_prtn_entry_domain_clst_referrerQuery extends hourly_ua_prtn_entry_domain_clst_referrerQuery
object minutely_ua_clst_applicationQuery extends minutely_ua_clst_applicationQuery
object hourly_ua_clst_applicationQuery extends hourly_ua_clst_applicationQuery
object minutely_ua_prtn_applicationQuery extends minutely_ua_prtn_applicationQuery
object hourly_ua_prtn_applicationQuery extends hourly_ua_prtn_applicationQuery
object minutely_ua_prtn_entry_clst_applicationQuery extends minutely_ua_prtn_entry_clst_applicationQuery
object hourly_ua_prtn_entry_clst_applicationQuery extends hourly_ua_prtn_entry_clst_applicationQuery
object minutely_ua_prtn_entry_applicationQuery extends minutely_ua_prtn_entry_applicationQuery
object hourly_ua_prtn_entry_applicationQuery extends hourly_ua_prtn_entry_applicationQuery
object minutely_ua_clst_playbackcontextQuery extends minutely_ua_clst_playbackcontextQuery
object hourly_ua_clst_playbackcontextQuery extends hourly_ua_clst_playbackcontextQuery
object minutely_ua_prtn_playbackcontextQuery extends minutely_ua_prtn_playbackcontextQuery
object hourly_ua_prtn_playbackcontextQuery extends hourly_ua_prtn_playbackcontextQuery
object minutely_ua_prtn_entry_clst_playbackcontextQuery extends minutely_ua_prtn_entry_clst_playbackcontextQuery
object hourly_ua_prtn_entry_clst_playbackcontextQuery extends hourly_ua_prtn_entry_clst_playbackcontextQuery
object minutely_ua_prtn_entry_playbackcontextQuery extends minutely_ua_prtn_entry_playbackcontextQuery
object hourly_ua_prtn_entry_playbackcontextQuery extends hourly_ua_prtn_entry_playbackcontextQuery
object minutely_ua_ptrn_application_clst_playbackcontextQuery extends minutely_ua_ptrn_application_clst_playbackcontextQuery
object hourly_ua_ptrn_application_clst_playbackcontextQuery extends hourly_ua_ptrn_application_clst_playbackcontextQuery
object minutely_ua_prtn_application_playbackcontextQuery extends minutely_ua_prtn_application_playbackcontextQuery
object hourly_ua_prtn_application_playbackcontextQuery extends hourly_ua_prtn_application_playbackcontextQuery
object minutely_ua_prtn_entry_application_clst_playbackcontextQuery extends minutely_ua_prtn_entry_application_clst_playbackcontextQuery
object hourly_ua_prtn_entry_application_clst_playbackcontextQuery extends hourly_ua_prtn_entry_application_clst_playbackcontextQuery
object minutely_ua_prtn_entry_application_playbackcontextQuery extends minutely_ua_prtn_entry_application_playbackcontextQuery
object hourly_ua_prtn_entry_application_playbackcontextQuery extends hourly_ua_prtn_entry_application_playbackcontextQuery
object minutely_ua_clst_cf1Query extends minutely_ua_clst_cf1Query
object hourly_ua_clst_cf1Query extends hourly_ua_clst_cf1Query
object minutely_ua_prtn_cf1Query extends minutely_ua_prtn_cf1Query
object hourly_ua_prtn_cf1Query extends hourly_ua_prtn_cf1Query
object minutely_ua_prtn_entry_clst_cf1Query extends minutely_ua_prtn_entry_clst_cf1Query
object hourly_ua_prtn_entry_clst_cf1Query extends hourly_ua_prtn_entry_clst_cf1Query
object minutely_ua_prtn_entry_cf1Query extends minutely_ua_prtn_entry_cf1Query
object hourly_ua_prtn_entry_cf1Query extends hourly_ua_prtn_entry_cf1Query
object minutely_ua_clst_cf2Query extends minutely_ua_clst_cf2Query
object hourly_ua_clst_cf2Query extends hourly_ua_clst_cf2Query
object minutely_ua_prtn_cf2Query extends minutely_ua_prtn_cf2Query
object hourly_ua_prtn_cf2Query extends hourly_ua_prtn_cf2Query
object minutely_ua_prtn_entry_clst_cf2Query extends minutely_ua_prtn_entry_clst_cf2Query
object hourly_ua_prtn_entry_clst_cf2Query extends hourly_ua_prtn_entry_clst_cf2Query
object minutely_ua_prtn_entry_cf2Query extends minutely_ua_prtn_entry_cf2Query
object hourly_ua_prtn_entry_cf2Query extends hourly_ua_prtn_entry_cf2Query
object minutely_ua_clst_cf3Query extends minutely_ua_clst_cf3Query
object hourly_ua_clst_cf3Query extends hourly_ua_clst_cf3Query
object minutely_ua_prtn_cf3Query extends minutely_ua_prtn_cf3Query
object hourly_ua_prtn_cf3Query extends hourly_ua_prtn_cf3Query
object minutely_ua_prtn_entry_clst_cf3Query extends minutely_ua_prtn_entry_clst_cf3Query
object hourly_ua_prtn_entry_clst_cf3Query extends hourly_ua_prtn_entry_clst_cf3Query
object minutely_ua_prtn_entry_cf3Query extends minutely_ua_prtn_entry_cf3Query
object hourly_ua_prtn_entry_cf3Query extends hourly_ua_prtn_entry_cf3Query
object minutely_ua_prtn_cf1_clst_cf2Query extends minutely_ua_prtn_cf1_clst_cf2Query
object hourly_ua_prtn_cf1_clst_cf2Query extends hourly_ua_prtn_cf1_clst_cf2Query
object minutely_ua_prtn_cf1_cf2Query extends minutely_ua_prtn_cf1_cf2Query
object hourly_ua_prtn_cf1_cf2Query extends hourly_ua_prtn_cf1_cf2Query
object minutely_ua_prtn_entry_cf1_clst_cf2Query extends minutely_ua_prtn_entry_cf1_clst_cf2Query
object hourly_ua_prtn_entry_cf1_clst_cf2Query extends hourly_ua_prtn_entry_cf1_clst_cf2Query
object minutely_ua_prtn_entry_cf1_cf2Query extends minutely_ua_prtn_entry_cf1_cf2Query
object hourly_ua_prtn_entry_cf1_cf2Query extends hourly_ua_prtn_entry_cf1_cf2Query
object minutely_ua_prtn_cf1_cf2_clst_cf3Query extends minutely_ua_prtn_cf1_cf2_clst_cf3Query
object hourly_ua_prtn_cf1_cf2_clst_cf3Query extends hourly_ua_prtn_cf1_cf2_clst_cf3Query
object minutely_ua_prtn_cf1_cf2_cf3Query extends minutely_ua_prtn_cf1_cf2_cf3Query
object hourly_ua_prtn_cf1_cf2_cf3Query extends hourly_ua_prtn_cf1_cf2_cf3Query
object minutely_ua_prtn_entry_cf1_cf2_clst_cf3Query extends minutely_ua_prtn_entry_cf1_cf2_clst_cf3Query
object hourly_ua_prtn_entry_cf1_cf2_clst_cf3Query extends hourly_ua_prtn_entry_cf1_cf2_clst_cf3Query
object minutely_ua_prtn_entry_cf1_cf2_cf3Query extends minutely_ua_prtn_entry_cf1_cf2_cf3Query
object hourly_ua_prtn_entry_cf1_cf2_cf3Query extends hourly_ua_prtn_entry_cf1_cf2_cf3Query
  val queries : List[IQuery] = List(
    hourly_ua_prtn_entryQuery,
minutely_ua_Query,
hourly_ua_Query,
minutely_ua_prtn_entryQuery,
minutely_ua_clst_entryQuery,
hourly_ua_clst_entryQuery,
minutely_ua_clst_countryQuery,
hourly_ua_clst_countryQuery,
minutely_ua_prtn_countryQuery,
hourly_ua_prtn_countryQuery,
minutely_ua_prtn_entry_clst_countryQuery,
hourly_ua_prtn_entry_clst_countryQuery,
minutely_ua_prtn_entry_countryQuery,
hourly_ua_prtn_entry_countryQuery,
minutely_ua_clst_country_cityQuery,
hourly_ua_clst_country_cityQuery,
minutely_ua_prtn_country_cityQuery,
hourly_ua_prtn_country_cityQuery,
minutely_ua_prtn_entry_clst_country_cityQuery,
hourly_ua_prtn_entry_clst_country_cityQuery,
minutely_ua_prtn_entry_country_cityQuery,
hourly_ua_prtn_entry_country_cityQuery,
minutely_ua_clst_deviceQuery,
hourly_ua_clst_deviceQuery,
minutely_ua_prtn_deviceQuery,
hourly_ua_prtn_deviceQuery,
minutely_ua_prtn_entry_clst_deviceQuery,
hourly_ua_prtn_entry_clst_deviceQuery,
minutely_ua_prtn_entry_deviceQuery,
hourly_ua_prtn_entry_deviceQuery,
minutely_ua_clst_osQuery,
hourly_ua_clst_osQuery,
minutely_ua_prtn_osQuery,
hourly_ua_prtn_osQuery,
minutely_ua_prtn_entry_clst_osQuery,
hourly_ua_prtn_entry_clst_osQuery,
minutely_ua_prtn_entry_osQuery,
hourly_ua_prtn_entry_osQuery,
minutely_ua_clst_browserQuery,
hourly_ua_clst_browserQuery,
minutely_ua_prtn_browserQuery,
hourly_ua_prtn_browserQuery,
minutely_ua_prtn_entry_clst_browserQuery,
hourly_ua_prtn_entry_clst_browserQuery,
minutely_ua_prtn_entry_browserQuery,
hourly_ua_prtn_entry_browserQuery,
minutely_ua_ptrn_device_clst_osQuery,
hourly_ua_ptrn_device_clst_osQuery,
minutely_ua_prtn_device_osQuery,
hourly_ua_prtn_device_osQuery,
minutely_ua_prtn_entry_device_clst_osQuery,
hourly_ua_prtn_entry_device_clst_osQuery,
minutely_ua_prtn_entry_device_osQuery,
hourly_ua_prtn_entry_device_osQuery,
minutely_ua_ptrn_os_clst_browserQuery,
hourly_ua_ptrn_os_clst_browserQuery,
minutely_ua_prtn_os_browserQuery,
hourly_ua_prtn_os_browserQuery,
minutely_ua_prtn_entry_os_clst_browserQuery,
hourly_ua_prtn_entry_os_clst_browserQuery,
minutely_ua_prtn_entry_os_browserQuery,
hourly_ua_prtn_entry_os_browserQuery,
hourly_ua_prtn_country_clst_os_browserQuery,
hourly_ua_prtn_country_clst_osQuery,
hourly_ua_prtn_country_clst_browserQuery,
minutely_ua_clst_domainQuery,
hourly_ua_clst_domainQuery,
minutely_ua_prtn_domainQuery,
hourly_ua_prtn_domainQuery,
minutely_ua_prtn_entry_clst_domainQuery,
hourly_ua_prtn_entry_clst_domainQuery,
minutely_ua_prtn_entry_domainQuery,
hourly_ua_prtn_entry_domainQuery,
minutely_ua_clst_referrerQuery,
hourly_ua_clst_referrerQuery,
minutely_ua_prtn_referrerQuery,
hourly_ua_prtn_referrerQuery,
minutely_ua_prtn_entry_clst_referrerQuery,
hourly_ua_prtn_entry_clst_referrerQuery,
minutely_ua_prtn_entry_referrerQuery,
hourly_ua_prtn_entry_referrerQuery,
minutely_ua_ptrn_domain_clst_referrerQuery,
hourly_ua_ptrn_domain_clst_referrerQuery,
minutely_ua_prtn_entry_domain_clst_referrerQuery,
hourly_ua_prtn_entry_domain_clst_referrerQuery,
minutely_ua_clst_applicationQuery,
hourly_ua_clst_applicationQuery,
minutely_ua_prtn_applicationQuery,
hourly_ua_prtn_applicationQuery,
minutely_ua_prtn_entry_clst_applicationQuery,
hourly_ua_prtn_entry_clst_applicationQuery,
minutely_ua_prtn_entry_applicationQuery,
hourly_ua_prtn_entry_applicationQuery,
minutely_ua_clst_playbackcontextQuery,
hourly_ua_clst_playbackcontextQuery,
minutely_ua_prtn_playbackcontextQuery,
hourly_ua_prtn_playbackcontextQuery,
minutely_ua_prtn_entry_clst_playbackcontextQuery,
hourly_ua_prtn_entry_clst_playbackcontextQuery,
minutely_ua_prtn_entry_playbackcontextQuery,
hourly_ua_prtn_entry_playbackcontextQuery,
minutely_ua_ptrn_application_clst_playbackcontextQuery,
hourly_ua_ptrn_application_clst_playbackcontextQuery,
minutely_ua_prtn_application_playbackcontextQuery,
hourly_ua_prtn_application_playbackcontextQuery,
minutely_ua_prtn_entry_application_clst_playbackcontextQuery,
hourly_ua_prtn_entry_application_clst_playbackcontextQuery,
minutely_ua_prtn_entry_application_playbackcontextQuery,
hourly_ua_prtn_entry_application_playbackcontextQuery,
minutely_ua_clst_cf1Query,
hourly_ua_clst_cf1Query,
minutely_ua_prtn_cf1Query,
hourly_ua_prtn_cf1Query,
minutely_ua_prtn_entry_clst_cf1Query,
hourly_ua_prtn_entry_clst_cf1Query,
minutely_ua_prtn_entry_cf1Query,
hourly_ua_prtn_entry_cf1Query,
minutely_ua_clst_cf2Query,
hourly_ua_clst_cf2Query,
minutely_ua_prtn_cf2Query,
hourly_ua_prtn_cf2Query,
minutely_ua_prtn_entry_clst_cf2Query,
hourly_ua_prtn_entry_clst_cf2Query,
minutely_ua_prtn_entry_cf2Query,
hourly_ua_prtn_entry_cf2Query,
minutely_ua_clst_cf3Query,
hourly_ua_clst_cf3Query,
minutely_ua_prtn_cf3Query,
hourly_ua_prtn_cf3Query,
minutely_ua_prtn_entry_clst_cf3Query,
hourly_ua_prtn_entry_clst_cf3Query,
minutely_ua_prtn_entry_cf3Query,
hourly_ua_prtn_entry_cf3Query,
minutely_ua_prtn_cf1_clst_cf2Query,
hourly_ua_prtn_cf1_clst_cf2Query,
minutely_ua_prtn_cf1_cf2Query,
hourly_ua_prtn_cf1_cf2Query,
minutely_ua_prtn_entry_cf1_clst_cf2Query,
hourly_ua_prtn_entry_cf1_clst_cf2Query,
minutely_ua_prtn_entry_cf1_cf2Query,
hourly_ua_prtn_entry_cf1_cf2Query,
minutely_ua_prtn_cf1_cf2_clst_cf3Query,
hourly_ua_prtn_cf1_cf2_clst_cf3Query,
minutely_ua_prtn_cf1_cf2_cf3Query,
hourly_ua_prtn_cf1_cf2_cf3Query,
minutely_ua_prtn_entry_cf1_cf2_clst_cf3Query,
hourly_ua_prtn_entry_cf1_cf2_clst_cf3Query,
minutely_ua_prtn_entry_cf1_cf2_cf3Query,
hourly_ua_prtn_entry_cf1_cf2_cf3Query
  )
}
