package com.kaltura.aggregations.keys

import org.joda.time.DateTime

case class AggregationEntryKey (partnerId: Int, entryId: String, metric: String, time: DateTime)
case class AggregationKey(partnerId: Int, metric: String, time: DateTime)
case class AggregationCountryKey(partnerId: Int, metric: String, time: DateTime, country: String)
case class AggregationCountryCityKey(partnerId: Int, metric: String, time: DateTime, country: String, city: String)
case class AggregationDomainKey(partnerId: Int, metric: String, time: DateTime, domain: String)
case class AggregationDomainReferrerKey(partnerId: Int, metric: String, time: DateTime, domain: String, referrer: String)
case class AggregationDeviceKey(partnerId: Int, metric: String, time: DateTime, device: Int)
case class AggregationOperatingSystemKey(partnerId: Int, metric: String, time: DateTime, operatingSystem: Int)
case class AggregationBrowserKey(partnerId: Int, metric: String, time: DateTime, browser: Int)
case class AggregationDeviceOperatingSystemKey(partnerId: Int, metric: String, time: DateTime, device: Int, operatingSystem: Int)
case class AggregationOperatingSystemBrowserKey(partnerId: Int, metric: String, time: DateTime, operatingSystem: Int, browser: Int)
case class AggregationCountryOperatingSystemBrowserKey(partnerId: Int, metric: String, time: DateTime, country: String, operatingSystem: Int, browser: Int)
case class AggregationCountryOperatingSystemKey(partnerId: Int, metric: String, time: DateTime, country: String, operatingSystem: Int)
case class AggregationCountryBrowserKey(partnerId: Int, metric: String, time: DateTime, country: String, browser: Int)
case class AggregationApplicationKey(partnerId: Int, metric: String, time: DateTime, application: String)
case class AggregationPlaybackContextKey(partnerId: Int, metric: String, time: DateTime, playbackContext: String)
case class AggregationApplicationPlaybackContextKey(partnerId: Int, metric: String, time: DateTime, application: String, playbackContext: String)
case class AggregationCustomVarKey(partnerId: Int, metric: String, time: DateTime, cv: String)
case class AggregationCustomVar1CustomVar2Key(partnerId: Int, metric: String, time: DateTime, cv1: String, cv2: String)
case class AggregationCustomVar1CustomVar2CustomVar3Key(partnerId: Int, metric: String, time: DateTime, cv1: String, cv2: String, cv3: String)
case class AggregationCategoryKey(partnerId: Int, metric: String, time: DateTime, category: String)
case class AggregationEntryApplicationKey(partnerId: Int, entryId: String, metric: String, time: DateTime, application: String)
case class AggregationEntryApplicationPlaybackContextKey(partnerId: Int, entryId: String, metric: String, time: DateTime, application: String, playbackContext: String)
case class AggregationEntryCountryKey(partnerId: Int, entryId: String, metric: String, time: DateTime, country: String)
case class AggregationEntryCountryCityKey(partnerId: Int, entryId: String, metric: String, time: DateTime, country: String, city: String)
case class AggregationEntryDomainKey(partnerId: Int, entryId: String, metric: String, time: DateTime, domain: String)
case class AggregationEntryDomainReferrerKey(partnerId: Int, entryId: String, metric: String, time: DateTime, domain: String, referrer: String)
case class AggregationEntryDeviceKey(partnerId: Int, entryId: String, metric: String, time: DateTime, device: Int)
case class AggregationEntryOperatingSystemKey(partnerId: Int, entryId: String, metric: String, time: DateTime, operatingSystem: Int)
case class AggregationEntryBrowserKey(partnerId: Int, entryId: String, metric: String, time: DateTime, browser: Int)
case class AggregationEntryDeviceOperatingSystemKey(partnerId: Int, entryId: String, metric: String, time: DateTime, device: Int, operatingSystem: Int)
case class AggregationEntryOperatingSystemBrowserKey(partnerId: Int, entryId: String, metric: String, time: DateTime, operatingSystem: Int, browser: Int)
case class AggregationEntryPlaybackContextKey(partnerId: Int, entryId: String, metric: String, time: DateTime, playbackContext: String)
case class AggregationEntryCustomVarKey(partnerId: Int, entryId: String, cv: String, metric: String, time: DateTime)
case class AggregationEntryCustomVar1CustomVar2Key(partnerId: Int, entryId: String, metric: String, time: DateTime, cv1: String, cv2: String)
case class AggregationEntryCustomVar1CustomVar2CustomVar3Key(partnerId: Int, entryId: String, metric: String, time: DateTime, cv1: String, cv2: String, cv3: String)
case class AggregationEntryCategoryKey(partnerId: Int, entryId: String, metric: String, time: DateTime, category: String)